{% set name = "eth-rlp" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3263b548df718855d9a8dbd754473f383c0efc82914b0b849572ce3e06e71a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
    - setuptools-markdown
  run:
    - eth-utils >=1.0.1,<2
    - hexbytes >=0.1.0,<1
    - python >=3.5,<4.0
    - rlp >=0.6.0,<2

test:
  imports:
    - eth_rlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-rlp
  summary: 'eth-rlp: RLP definitions for common Ethereum objects in Python'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
